[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "duckduckgo-search>=7.5.2",
    "openai>=1.66.3",
    "pandas>=2.2.3",
    "streamlit>=1.43.2",
    "trafilatura>=2.0.0",
]
